# Generated by Django 4.2.5 on 2023-09-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тарифа')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Описание тарифа')),
                ('features', models.CharField(max_length=255, null=True, verbose_name='Опции тарифа')),
                ('benefits', models.CharField(max_length=255, null=True, verbose_name='Дополнительно к тарифу')),
                ('price', models.CharField(max_length=255, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['name'],
            },
        ),
    ]
