# Generated by Django 4.2.5 on 2023-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='price',
        ),
        migrations.AddField(
            model_name='tariff',
            name='main_price',
            field=models.CharField(max_length=255, null=True, verbose_name='Основная цена'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='price_annotation',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительные условия'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='sale_price',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
